RecipeViewerEvents.addInformation('item', (event) => {
    // https://kubejs.com/wiki/events/RecipeViewerEvents/addInformation

    /* Format Codes
    Obfuscated      §k
    Bold            §l
    Strikethrough   §m
    Underline       §n
    Italic          §o
    Reset Format    §r

    Colors:
    Dark Red        §4
    Red             §c
    Gold            §6
    Yellow          §e
    Dark Green      §2
    Green           §a
    Aqua            §b
    Dark Aqua       §3
    Dark Blue       §1
    Blue            §9
    Light Purple    §d
    Dark Purple 	§5
    White           §f
    Gray            §7
    Dark Gray       §8
    Black           §0

    */
    const descriptions = [
        {
            filter: ['ae2:sky_dust'],
            text: ['Sky Dust can be generated by pointing an Annihilation Plane at the sky at build limit (§2Y=319§r).']
        },
        {
            filter: beheading_tools,
            text: ['Easily cleaves the heads from your foes!']
        },
        {
            filter: [
                'minecraft:zombie_head',
                'minecraft:creeper_head',
                'minecraft:piglin_head',
                'minecraft:dragon_head',
                'minecraft:skeleton_skull',
                'minecraft:wither_skeleton_skull',
                'enderio:enderman_head'
            ],
            text: [
                'Heads may be obtained from mobs by killing them with particularly powerful axes and paxels.',
                ' ',
                'Search for §5#beheading§r in EMI for a list!'
            ]
        },

        {
            filter: ['enderio:industrial_insulation_block'],
            text: ['Absorbs and voids any fluids placed nearby.']
        },
        {
            filter: ['naturesaura:vacuum_bottle'],
            text: [
                'Use a Bottle and Cork in an area devoid of Aura.',
                ' ',
                `Can be automated using a JustDireThings Clicker.`
            ]
        },
        {
            filter: [
                Item.of('naturesaura:aura_bottle[naturesaura:aura_bottle_data={aura_type:"naturesaura:overworld"}]')
            ],
            text: [
                'Use a Bottle and Cork in an area of high Aura in the Overworld.',
                ' ',
                `Can be automated using a JustDireThings Clicker.`
            ]
        },

        {
            filter: ['naturesaura:gold_leaf'],
            text: [`Obtained by breaking Golden Leaves.`]
        },
        {
            filter: ['naturesaura:golden_leaves'],
            text: [`Obtained by using Brilliant Fiber on leaves. Allow to spread for best effect.`]
        },
        {
            filter: ['naturesaura:break_prevention'],
            text: [
                `When applied to a tool in an anvil, the tool will stop working when durability runs out instead of being destroyed.`
            ]
        },
        {
            filter: ['naturesaura:birth_spirit'],
            text: [`Obtained by manually breeding animals in high Aura areas.`]
        },
        {
            filter: ['naturesaura:projectile_generator'],
            text: [
                `May be automated with a Supplementaries Cannon.`,
                ` `,
                `Valid projectiles:`,
                ` `,
                `● Snowball:                7K`,
                `● Egg:                      10K`,
                `● Arrow:                30K`,
                `● Fire Charge:          35K`,
                `● Cannonball:             35K`,
                `● Spectral Arrow:        40K`,
                `● Ender Pearl:            50K`,
                `● Llama Spit:             100K`,
                `● Bottle o' Enchanting: 200K`,
                `● Shulker Bullet:       300K`,
                `● Trident:                 3M`
            ]
        },
        {
            filter: ['industrialforegoing:ether_gas_bucket'],
            text: [
                `Enables auto-harvesting in the Hydroponic Bed.`,
                ` `,
                `Enables 5x Ore Multiplier in the Fermentation Station.`,
                ` `,
                `Enables gentle-harvesting in the Plant Gatherer.`
            ]
        },
        {
            filter: ['#malum:strange_materials'],
            text: [`May appear when using Bone Meal on Blighted land.`]
        },
        {
            filter: ['#industrialforegoing:sludge'],
            text: [`May be produced in a Sludge Refiner. Sludge is a by-product of the Plant Gatherer.`]
        },
        {
            filter: [
                'handcrafted:pillager_trophy',
                'handcrafted:vindicator_trophy',
                'handcrafted:evoker_trophy',
                'handcrafted:witch_trophy'
            ],
            text: [`Right-Click with an Antikythera Mechanism to bring it to life!`]
        },
        {
            filter: ['enigmatica:antikythera_mechanism'],
            text: [`Right-Click an Illager Trophy to bring it to life!`]
        },
        {
            filter: ['naturesaura:token_grief'],
            text: [
                `Drops from a Clockwork Witch.`,
                ` `,
                `Right-Click a Witch Trophy with an Antikythera Mechanism to bring it to life!`
            ]
        },
        {
            filter: ['naturesaura:token_euphoria'],
            text: [
                `Drops from a Clockwork Evoker.`,
                ` `,
                `Right-Click an Evoker Trophy with an Antikythera Mechanism to bring it to life!`
            ]
        },
        {
            filter: ['naturesaura:token_rage'],
            text: [
                `Drops from a Clockwork Vindicator.`,
                ` `,
                `Right-Click a Vindicator Trophy with an Antikythera Mechanism to bring it to life!`
            ]
        },
        {
            filter: ['naturesaura:token_terror'],
            text: [
                `Drops from a Clockwork Pillager.`,
                ` `,
                `Right-Click a Pillager Trophy with an Antikythera Mechanism to bring it to life!`
            ]
        },
        {
            filter: [
                Ingredient.of(['arts_and_crafts:lotus_pistils', 'minecraft:lily_pad', 'arts_and_crafts:bleachdew'])
            ],
            text: [
                `Lotus Pistils may be planted on Lily Pads to convert them into a Lotus Flower.`,
                ` `,
                `Use Bone Meal on a Lotus Flower to obtain Bleachdew.`
            ]
        }
    ];

    Object.keys(spiritEntities).forEach((type) => {
        let description = { filter: [`malum:${type}_spirit`], text: ['Obtained from the following mobs:'] };
        let previous_mod = '';

        spiritEntities[type].sort().forEach((entity) => {
            let current_mod = entity.split(':')[0];
            if (current_mod != previous_mod) {
                previous_mod = current_mod;

                if (current_mod == 'creeperoverhaul') {
                    current_mod = 'Creeper Overhaul';
                } else if (current_mod == 'sushigocrafting') {
                    current_mod = 'Sushi Go Crafting';
                } else {
                    current_mod = toTitleCase(current_mod.replace('_', ' '));
                }

                description.text.push(' ', `${current_mod}`);
            }
            description.text.push(Text.string(' ● ').append(Text.translate(`entity.${entity.replace(':', '.')}`)));
        });
        descriptions.push(description);
    });

    Object.keys(essenceEntities).forEach((type) => {
        let description = { filter: [type], text: ['Obtained from the following mobs:'] };
        let previous_mod = '';

        essenceEntities[type].sort().forEach((entity) => {
            let current_mod = entity.split(':')[0];
            if (current_mod != previous_mod) {
                previous_mod = current_mod;

                if (current_mod == 'creeperoverhaul') {
                    current_mod = 'Creeper Overhaul';
                } else if (current_mod == 'sushigocrafting') {
                    current_mod = 'Sushi Go Crafting';
                } else {
                    current_mod = toTitleCase(current_mod.replace('_', ' '));
                }

                description.text.push(' ', `${current_mod}`);
            }
            description.text.push(Text.string(' ● ').append(Text.translate(`entity.${entity.replace(':', '.')}`)));
        });
        descriptions.push(description);
    });

    Object.keys(villagerTrades).forEach((profession) => {
        villagerTrades[profession].forEach((recipe) => {
            // "entity.minecraft.villager.farmer"
            // "entity.minecraft.villager.actuallyadditions.engineer"

            let lang_key = `entity.minecraft.villager.${profession.replace('minecraft:', '').replace(':', '.')}`;

            descriptions.push({
                filter: [Item.of(recipe.result.id)],
                text: [
                    Text.string(`Obtained by trading with `)
                        .append(Text.translate(lang_key))
                        .append(Text.string(' Villagers.')),

                    ` `,
                    Text.string(`Trade Level: `).append(Text.translate(`merchant.level.${recipe.level}`))
                ]
            });
        });
    });

    descriptions.forEach((description) => {
        event.add(description.filter, description.text);
    });
});
