ServerEvents.recipes((event) => {
    const recipes = [
        // {
        //     input: 'sample',
        //     output: 'sample',
        //     type: 'sample',
        //     mod: 'sample',
        //     id: 'sample'
        // }

        // Actually Additions
        { output: 'actuallyadditions:rice_slimeball' },
        { type: 'actuallyadditions:mining_lens' },
        { type: 'actuallyadditions:pressing' },
        { type: 'actuallyadditions:crushing' },
        { type: 'actuallyadditions:empowering' },
        { id: 'actuallyadditions:lens_of_the_miner' },
        { id: 'actuallyadditions:lens_of_the_killer' },
        { id: /actuallyadditions:crushing\/.*_horse_armor/ },
        { id: /actuallyadditions:crushing\/.*_ore$/ },
        { id: /actuallyadditions:laser\/crystalize_(diamatine|emeradic|enori|palis|restonia|void)/ },
        { id: 'actuallyadditions:crushing/block_coal' },
        { id: 'actuallyadditions:coal_generator' },
        { id: 'actuallyadditions:oil_generator' },
        { id: 'actuallyadditions:basic_coil' },
        { id: 'actuallyadditions:vertical_digger' },
        { id: 'actuallyadditions:laser/nether_wart' },
        { id: 'actuallyadditions:laser/ethetic_green_block' },
        { id: 'actuallyadditions:laser/ethetic_white_block' },
        { id: `actuallyadditions:rice_dough` },
        { id: `actuallyadditions:rice_paper` },
        { id: `actuallyadditions:wood_casing` },
        { id: `actuallyadditions:iron_casing` },
        { id: `actuallyadditions:empty_cup` },
        { id: `actuallyadditions:coffee_machine` },
        { id: `actuallyadditions:canola_press` },
        { id: `actuallyadditions:tagged_sticky_piston` },
        { id: `actuallyadditions:greenhouse_glass` },

        // Aether
        { id: 'aether:golden_aercloud_enchanting' },
        { id: 'aether:swet_slime_block' },
        { id: 'aether:swet_sticky_piston' },
        { id: 'aether:swet_lead' },
        { id: 'aether:moa_egg_pumpkin_pie' },

        // Applied Energistics and Addons
        { id: /ae2:(smelting|blasting)\/silicon/ },
        { id: 'ae2:charger/charged_certus_quartz_crystal' },
        { id: /ae2:transform\/.*(quartz|fluix)/ },
        { id: /advanced_ae:.*budding/ },
        { id: 'advanced_ae:redstonecrystal' },
        { id: 'advanced_ae:certuscharger' },
        { id: 'advanced_ae:quartzcrystal' },
        { id: 'advanced_ae:fluixcrystals' },
        { id: 'advanced_ae:fluixcrystalfromdust' },

        // Aquaculture
        { id: 'aquaculture:gold_nugget_from_gold_fish' },
        { id: 'aquaculture:jellyfish_to_slimeball' },

        // Ars Nouveau and Addons
        { type: 'ars_nouveau:glyph' },
        { type: 'ars_nouveau:alakarkinos_conversion' },
        { id: `ars_nouveau:imbuement_chamber` },
        { id: /ars_nouveau:.*_sourcelink/ },
        { id: `ars_nouveau:enchanting_apparatus` },
        { id: `ars_nouveau:arcane_core` },
        { id: `ars_nouveau:storage_lectern` },
        { id: `ars_nouveau:repository` },
        { id: `ars_nouveau:repository_controller` },
        { id: `ars_nouveau:source_berry_roll` },
        { id: `ars_nouveau:ritual_brazier` },
        { id: `ars_caelum:heart_of_the_sea` },
        { id: /ars_nouveau:(cobblestone|stone|sand|gravel)/ },
        { id: /ars_nouveau:imbuement_(fire|air|water|earth)_essence/ },
        { id: /ars_(nouveau|elemental):imbuement_(manipulation|conjuration|abjuration|anima)_essence/ },
        { id: /ars_nouveau:imbuement_(lapis|amethyst)/ },
        { id: /arsdelight:cooking\/cooking\/.*_jelly/ },
        {
            output: /ars.*:ritual_(awakening|challenge|burrowing|animal_summon|elder_summon|mana_regeneration|sedimentation)/
        },
        { id: 'ars_nouveau:source_berry_pie' },
        { id: 'arsdelight:mendosteen_pie' },
        { id: 'arsdelight:bastion_pie' },
        { id: 'arsdelight:bombegrante_pie' },
        { id: 'arsdelight:frostaya_pie' },
        { id: 'ars_elemental:wool_to_string' },
        { id: /ars_caelum:ritual_conjure_island_(flourishing|cascading|blazing|vexing|geode)/ },

        // Create and Addons
        { id: /create:crushing\/raw_/ },
        { id: /create:mixing\/(andesite_alloy|brass_ingot)/ },
        { id: /create:item_application\/(andesite|brass|copper)_casing/ },
        { id: 'create:crafting/materials/rose_quartz' },
        { id: 'create:crafting/materials/andesite_alloy' },
        { id: 'create:crafting/materials/andesite_alloy_from_zinc' },
        { id: 'create:crafting/appliances/slime_ball' },
        { id: 'create:crafting/appliances/chain_from_zinc' },
        { id: 'create:crafting/appliances/dough' },
        { id: /create:crushing\/(gravel|asurine|diorite|veridium|crimsite|ochrum|tuff)/ },
        { id: /create:crushing\/.*_horse_armor/ },
        { id: 'create:crushing/prismarine_crystals' },
        { id: 'create:crushing/gilded_blackstone' },
        { id: 'create:mixing/compat/ae2/fluix_crystal' },
        { id: /create:milling\/(dripstone|cobblestone|andesite|calcite|granite|saddle)/ },
        { id: 'create:crafting/kinetics/large_cogwheel' },
        { id: 'create:crafting/materials/electron_tube' },
        { id: 'create:sequenced_assembly/precision_mechanism' },
        { id: /create:splashing\/crushed_raw_.*/ },
        { id: /create:splashing\/(red_sand|gravel)/ },
        { id: /create:smelting\/.*_ingot_from_crushed/ },

        { type: 'createsifter:sifting' },
        { id: /createsifter:(crushing|milling)/ },
        { id: /createsifter:shapeless\/raw_.*_piece/ },

        { id: 'trading_floor:trading_depot' },

        // EnderIO
        { type: 'enderio:fire_crafting' },
        { output: 'enderio:wood_gear' },
        { output: 'enderio:stirling_generator' },
        { id: 'enderio:sag_milling/cobbled_deepslate' },
        { id: 'enderio:sag_milling/flower_pot' },
        { id: /enderio:sag_milling\/raw_/ },
        { type: 'enderio:alloy_smelting', id: /enderio:.*dark_steel_ingot/ },
        { id: /enderio:alloy_smelting\/(redstone|pulsating|conductive)_alloy_ingot/ },
        { id: /enderio:alloy_smelting\/(copper|energetic|vibrant)_alloy_ingot/ },
        { id: /enderio:alloy_smelting\/(soularium|end_steel)_ingot/ },
        { id: 'enderio:alloy_smelting/industrial_insulation_block' },
        { id: 'enderio:pulsating_crystal' },
        { id: `enderio:primitive_alloy_smelter` },
        { id: 'enderio:slice_and_splice' },
        { id: 'enderio:ensouled_chassis' },
        { id: 'enderio:soul_chain' },
        { id: 'enderio:soulbinding/frank_n_zombie' },
        { id: 'enderio:slicing/z_logic_controller' },
        { id: 'enderio:slicing/guardian_diode' },

        // Enigmatic Unity
        { mod: 'enigmaticunity' },

        // Farmers Delight
        { output: 'farmersdelight:organic_compost' },
        { id: 'farmersdelight:wheat_dough_from_water' },
        { id: 'farmersdelight:wheat_dough_from_egg' },
        { id: 'farmersdelight:pie_crust' },
        { id: 'farmersdelight:apple_pie' },
        { id: 'farmersdelight:chocolate_pie' },
        { id: 'farmersdelight:integration/create/mixing/pie_crust_from_mixing' },

        { output: 'framedblocks:phantom_paste' },

        // Genetics
        { output: 'geneticsresequenced:coal_generator' },
        { output: `geneticsresequenced:cell_analyzer` },
        { output: `geneticsresequenced:dna_extractor` },
        { output: `geneticsresequenced:dna_decryptor` },
        { output: `geneticsresequenced:blood_purifier` },
        { output: `geneticsresequenced:plasmid_infuser` },
        { output: `geneticsresequenced:incubator` },
        { output: `geneticsresequenced:advanced_incubator` },
        { output: `geneticsresequenced:plasmid_injector` },
        { output: `geneticsresequenced:scraper` },
        { output: `geneticsresequenced:syringe` },
        { output: `geneticsresequenced:metal_syringe` },
        { output: `geneticsresequenced:gene_checker` },
        { output: `geneticsresequenced:overclocker` },
        { id: `geneticsresequenced:incubator/gmo/mutation/flight_from_ender_dragon_with_55_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/speed_2_from_rabbit_with_50_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/efficiency_4_from_silverfish_with_25_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/regeneration_4_from_ender_dragon_with_35_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/speed_4_from_ocelot_with_50_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/claws_2_from_polar_bear_with_75_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/strength_2_from_polar_bear_with_50_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/more_hearts_2_from_enderman_with_25_chance` },
        { id: `geneticsresequenced:incubator/gmo/mutation/resistance_2_from_shulker_with_50_chance` },
        { id: `geneticsresequenced:incubator/gmo/keep_inventory_from_shulker_with_45_chance` },
        { id: `geneticsresequenced:incubator/gmo/more_hearts_from_enderman_with_20_chance` },
        { id: `geneticsresequenced:incubator/gmo/regeneration_from_iron_golem_with_30_chance` },

        // Industrial Foregoing
        { type: 'industrialforegoing:fluid_extractor' },
        { type: 'industrialforegoing:laser_drill_ore' },
        { type: 'industrialforegoing:bioreactor' },
        { output: 'industrialforegoing:pitiful_generator' },
        { output: 'industrialforegoing:fluid_extractor' },
        { output: 'industrialforegoing:biofuel_generator' },
        { output: 'industrialforegoing:bioreactor' },
        { output: 'industrialforegoing:water_condensator' },
        { output: 'industrialforegoing:ore_laser_base' },
        { output: 'industrialforegoing:latex_processing_unit' },
        { output: 'industrialforegoing:animal_feeder' },
        { input: 'industrialforegoing:dryrubber' },
        { id: 'industrialforegoing:dissolution_chamber/mechanical_dirt' },
        { id: 'industrialforegoing:dissolution_chamber/simple_machine_frame' },
        { id: /industrialforegoing:dissolution_chamber\/range_addon_tier/ },
        { id: 'industrialforegoing:laser_drill_fluid/ether' },

        // Just Dire Things
        { output: /justdirethings:gooblock/ },
        { output: 'justdirethings:generatort1' },
        { output: 'justdirethings:generatorfluidt1' },
        { output: 'justdirethings:polymorphic_catalyst' },
        { id: /justdirethings:raw_coal_t(1|2)_ore-goospread/ },
        { id: /justdirethings:.*refined_t[0-9]_fluid_block-(goospread|fluiddrop)/ },

        // Malum
        { id: /malum:create\/washing\/.*_node/ },
        { id: /malum:create\/washing\/crushed_.*/ },
        { id: /malum:uranium_from_node_(smelting|blasting)/ },
        { id: /malum:create\/crushing\/ore/ },
        { id: 'malum:void_favor/raw_soulstone' },
        { id: 'malum:void_favor/anomalous_design' },
        { id: 'malum:spirit_infusion/soul_stained_steel_ingot' },
        { id: 'malum:spirit_infusion/imitation_flesh' },
        { id: /malum:spirit_infusion\/.*_spirited_glass/ },

        // Minecraft
        { id: 'minecraft:slime_block' },
        { id: 'minecraft:nether_brick' },
        { id: 'minecraft:netherite_ingot' },
        { id: 'minecraft:pumpkin_pie' },
        { id: 'minecraft:bread' },
        { output: 'minecraft:chest' },
        { output: /minecraft:infested/ },
        { output: /minecraft:(blast_furnace|furnace|smoker|cauldron|grindstone|loom)/ },
        { output: /minecraft:(composter|barrel|stonecutter|lectern|smithing_table|brewing_stand)/ },

        // Modern Industrialization and Addons
        { type: 'modern_industrialization:forge_hammer' },
        { output: 'modern_industrialization:fire_clay_dust' },
        { input: 'modern_industrialization:fire_clay_dust' },
        { output: /modern_industrialization:(brick|brick_tiny)_dust/ },
        { input: /modern_industrialization:(brick|brick_tiny)_dust/ },
        { type: 'minecraft:crafting_shaped', output: /modern_industrialization:.*_(gear|rotor|ring)$/ },
        {
            type: 'modern_industrialization:macerator',
            input: /(modern|extended)_industrialization:.*_(curved_plate|bolt)$/
        },
        { id: /modern_industrialization:materials\/.*\/macerator\/(raw_metal|crushed_dust)/ },
        { id: /modern_industrialization:materials\/macerator\/.*crushed_to_dust/ },
        { output: /(modern|extended)_industrialization:.*_(curved_plate|bolt)$/ },
        { output: `modern_industrialization:bronze_compressor` },
        { id: `modern_industrialization:vanilla_recipes/mixer/netherite` },
        { output: /modern_industrialization:.*_water_pump/ },
        { output: /extended_industrialization:.*_alloy_smelter/ },
        { output: `modern_industrialization:heatproof_machine_casing` },
        {
            type: 'modern_industrialization:mixer',
            output: /(cupronickel|bronze|cupronickel_ingot|electrum|invar|battery_alloy)_(dust|tiny_dust)/
        },
        { type: 'modern_industrialization:blast_furnace', output: '#c:ingots/steel' },
        { type: 'extended_industrialization:alloy_smelter' },
        { output: 'modern_industrialization:analog_circuit' },
        { output: 'modern_industrialization:bronze_machine_casing_pipe' },
        { output: 'modern_industrialization:motor' },
        { output: 'modern_industrialization:electronic_circuit' },
        { output: /modern_industrialization:(lv|mv)_steam_turbine/ },
        { output: /modern_industrialization:(tin|silver|electrum)_cable/ },
        { output: /modern_industrialization:(copper|cupronickel)_cable/ },
        { id: 'modern_industrialization:steam_age/bronze/machine_casing_asbl' },
        { id: 'modern_industrialization:steam_age/steel/machine_casing_asbl' },
        { id: 'modern_industrialization:assembler_generated/steam_age/bronze/machine_casing' },
        { id: 'modern_industrialization:assembler_generated/steam_age/steel/machine_casing' },
        { id: 'modern_industrialization:alloy/mixer/stainless_steel/dust' },
        { id: /modern_industrialization:dyes\/.*\/(craft|assembler)\/fluid_pipe_stained_glass/ },
        { id: /modern_industrialization:dyes\/.*\/(craft|assembler)\/item_pipe_direct/ },
        { id: /modern_industrialization:steam_age\/(fluid|item)_pipe_asbl/ },
        { id: /modern_industrialization:assembler_generated\/steam_age\/(fluid|item)_pipe/ },
        { id: /modern_industrialization:compat\/ae2\/(electrolyzer|mixer)/ },

        // Nature's Aura
        { type: 'naturesaura:animal_spawner' },
        { id: /naturesaura:tree_ritual\/token_/ },
        { id: /naturesaura:dimension_rail/ },
        { id: /naturesaura:(cave|fortress|end_city|outpost|loot|netherite)_finder/ },
        { id: 'naturesaura:rf_converter' },
        { id: 'naturesaura:spawn_lamp' },
        { id: 'naturesaura:chunk_loader' },
        { id: 'naturesaura:oak_generator' },
        { id: 'naturesaura:depth_ingot_creation' },
        { id: 'naturesaura:tree_ritual/nature_altar' },
        { id: 'naturesaura:tree_ritual/crushing_catalyst' },
        { id: 'naturesaura:tree_ritual/conversion_catalyst' },
        { id: 'naturesaura:tree_ritual/ore_spawn_powder' },
        { id: 'naturesaura:tree_ritual/animal_powder' },
        { id: 'naturesaura:blast_furnace_booster' },
        { id: `naturesaura:altar/coal` },
        { id: `naturesaura:altar/infused_stone` },
        { id: `naturesaura:altar/nether_wart` },
        { id: `naturesaura:altar/warped_fungus` },
        { id: `naturesaura:altar/crimson_fungus` },

        // Occultism
        { type: 'occultism:miner' },
        { type: 'occultism:crushing' },
        { type: 'occultism:crystallize' },
        { type: 'occultism:ritual' },
        { id: 'occultism:ritual/craft_soul_gem' },
        { id: 'occultism:ritual/craft_fragile_soul_gem' },
        { id: 'occultism:spirit_fire/otherworld_ashes' },

        // Oritech
        { type: 'oritech:foundry' },
        { type: 'oritech:fuel_generator' },
        { output: 'oritech:foundry_block' },
        { type: 'oritech:pulverizer' },
        { output: 'oritech:pulverizer_block' },
        { output: 'oritech:assembler_block' },
        { output: /oritech:.*_generator_block/ },
        { output: 'oritech:big_solar_panel_block' },
        { output: 'oritech:steam_engine_block' },
        { output: 'oritech:steam_boiler_addon' },
        { output: 'oritech:plastic_sheet' },
        // { output: /oritech:machine_core_/ },
        { id: 'oritech:silicon_blockblock' },
        { id: 'oritech:steel_ingot_from_blasting_steel_dust' },
        { id: 'oritech:crafting/alloy/steel' },
        { id: 'oritech:crafting/claybeads' },
        { id: 'oritech:crafting/witherrose' },
        { id: 'oritech:crafting/manualresin' },
        { id: 'oritech:crafting/alloy/rawsilicon' },
        { id: 'oritech:crafting/alloy/adamant' },
        { id: /oritech:(particle|laser)\/fluxite/ },
        { id: /oritech:(crafting|assembler)\/magnet/ },
        { id: 'oritech:compat/ae2/charger/fluxite' },
        { id: 'oritech:laser/compat/ae2/chargedquartz' },
        { id: 'oritech:compat/enderio/alloy/steel' },
        { id: 'oritech:cooler/compat/pneumaticcraft/plastic' },
        { id: 'oritech:mixing/compat/create/steel' },
        { id: 'oritech:assembler/fluxgate' },
        { id: 'oritech:assembler/claybeads' },
        { id: /oritech:centrifuge.*clump/ },
        { id: 'oritech:centrifuge/carbon' },
        { id: 'oritech:centrifuge/fluid/compat/pneumaticcraft/fuel' },
        { id: 'oritech:centrifuge/fluid/fuel' },
        { id: 'oritech:centrifuge/fluid/batteryacid' },
        { id: 'oritech:centrifuge/fluid/advbatteryacid' },
        { id: 'oritech:centrifuge/fluid/plasticoil' },
        { id: 'oritech:centrifuge/fluid/plasticbio' },
        { id: 'oritech:centrifuge/fluid/plasticoilbetter' },
        { id: 'oritech:centrifuge/fluid/plasticbiobetter' },
        { id: 'oritech:centrifuge/fluid/naptharesin' },
        { id: 'oritech:centrifuge/fluid/siliconwashbad' },
        { id: 'oritech:centrifuge/fluid/siliconwash' },
        { id: 'oritech:centrifuge/fluid/compat/industrialforegoing/turbofuel' },
        { id: 'oritech:centrifuge/fluid/compat/clumpwet/crushed_uranium' },
        { id: /oritech:refinery\/rawsheol\/(platinum|zinc|nickel)/ },
        { id: /oritech:refinery\/(biodiesel|heavyoil|oil|lava|carbonsheet)/ },
        { id: /oritech:splashing\/compat\/create/ },
        { id: 'oritech:atomicforge/urandust' },
        { id: /oritech:grinder\/uraniumcrystal/ },
        { id: /oritech:mixing\/compat\/create/ },
        { id: /oritech:compat\/enderio\/alloy/ },
        { input: /oritech:(nickel|platinum|iron|copper|gold)_gem/ },
        { id: /oritech:atomicforge\/dust\/(nickel|platinum|iron|copper|gold)/ },
        { id: /oritech:grinder\/raw\/(nickel|platinum|iron|copper|gold)/ },
        { id: /oritech:(nickel|platinum|iron|copper|gold)_clump/ },

        // PneumaticCraft
        { type: 'pneumaticcraft:explosion_crafting' },
        { type: 'pneumaticcraft:fuel_quality' },
        { output: 'pneumaticcraft:reinforced_stone' },
        { output: 'pneumaticcraft:crop_support' },
        { output: /pneumaticcraft:.*(air|flux|manual|solar)_compressor/ },
        { id: /pneumaticcraft:thermo_plant\/vegetable_oil/ },

        // PrettyPipes and Addons
        { output: 'prettypipes:pipe' },
        { output: 'prettypipes:blank_module' },
        { output: 'ppfluids:fluid_pipe' },

        // Replication
        { type: 'replication:matter_value' },

        // Supplementaries
        { id: 'supplementaries:statue' },
        { id: 'supplementaries:ash_brick' },

        // Tempad
        { id: 'tempad:time_steel_create' },

        // Theurgy
        { type: 'theurgy:digestion' },
        { type: 'theurgy:fermentation' },
        { type: 'theurgy:distillation' },
        { type: 'theurgy:calcination' },
        { type: 'theurgy:incubation' },
        { output: 'theurgy:sal_ammoniac_accumulator' },
        { output: 'theurgy:sal_ammoniac_tank' },
        { output: 'theurgy:pyromantic_brazier' },
        { output: 'theurgy:calcination_oven' },
        { output: 'theurgy:fermentation_vat' },
        { output: 'theurgy:digestion_vat' },
        { output: 'theurgy:distiller' },

        // Utilitarian
        { mod: 'utilitarian', id: /snad/ },
        { output: /soliciting_carpet/ },
        { output: 'utilitarian:drit' },
        { output: 'utilitarian:grrass' },
        { id: 'utilitarian:utility/green_dye' },
        { id: 'utilitarian:utility/bread' },
        { output: 'utilitarian:angel_block' },

        // Ore Processing Removals
        { input: '#c:ores' },
        { input: '#c:raw_materials/uranium' },
        { input: '#c:storage_blocks/raw_uranium' }
    ];

    recipes.forEach((recipe) => {
        event.remove(recipe);
    });
});
